# Generated by Django 4.0.4 on 2022-07-26 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_staff',
            field=models.BooleanField(db_index=True, default=False, verbose_name='права просмотра сайта администратора'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(db_index=True, default=False, verbose_name='права администратора'),
        ),
    ]
